#ifndef THUNDERDISPLAY_VERSION_H
#define THUNDERDISPLAY_VERSION_H
#define TD_VERSION_TEXT "0.8.1"
#define TD_VERSION_WIDE L"0.8.1"
#define TD_VERSION_RESOURCE "0.8.1\0"
#define TD_VERSION_NUMBERS 0,8,1,0
#endif
