// Synthetic TCP throughput test. Sends generated bytes only to the known TD peer.
#include <arpa/inet.h>
#include <netinet/tcp.h>
#include <poll.h>
#include <sys/socket.h>
#include <sys/resource.h>
#include <pthread/qos.h>
#include <unistd.h>
#include <fcntl.h>
#include <cerrno>
#include <algorithm>
#include <array>
#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <stdexcept>
#include <thread>
#include <vector>
using Clock = std::chrono::steady_clock;
static uint16_t read16(const unsigned char* p) { return uint16_t((p[0] << 8) | p[1]); }
static uint32_t read32(const unsigned char* p) { return (uint32_t(read16(p)) << 16) | read16(p + 2); }
struct Lane { int fd; uint64_t bytes=0; bool failed=false; };
static void describe(int fd, const char* stage) {
    tcp_connection_info info{}; socklen_t length=sizeof(info);
    int capacity=0, service=-1; socklen_t option=sizeof(capacity);
    getsockopt(fd,SOL_SOCKET,SO_SNDBUF,&capacity,&option);
    option=sizeof(service); getsockopt(fd,SOL_SOCKET,SO_NET_SERVICE_TYPE,&service,&option);
    if(getsockopt(fd,IPPROTO_TCP,TCP_CONNECTION_INFO,&info,&length)==0) {
        printf("tcp stage=%s fd=%d qos=%u process_bg=%d thread_bg=%d service=%d mss=%u receiver=%u scale=%u congestion=%u buffered=%u/%d rtt_ms=%u retransmitted=%llu\n",stage,fd,unsigned(qos_class_self()),
            getpriority(PRIO_DARWIN_PROCESS,getpid()),getpriority(PRIO_DARWIN_THREAD,0),service,info.tcpi_maxseg,info.tcpi_snd_wnd,
            info.tcpi_snd_wscale,info.tcpi_snd_cwnd,info.tcpi_snd_sbbytes,capacity,info.tcpi_srtt,
            static_cast<unsigned long long>(info.tcpi_txretransmitbytes)); fflush(stdout);
    }
}
int main(int argc, char** argv) {
    const bool loopback = argc == 2 && std::strcmp(argv[1], "--loopback-check") == 0;
    if (argc > 1 && !loopback) return 2;
    const char* local = loopback ? "127.0.0.1" : "10.0.0.2";
    const char* peer = loopback ? "127.0.0.1" : "10.0.0.3";
    const uint32_t duration = loopback ? 1000 : 8000;
    printf("runtime qos=%u process_bg=%d thread_bg=%d nice=%d\n",unsigned(qos_class_self()),getpriority(PRIO_DARWIN_PROCESS,getpid()),getpriority(PRIO_DARWIN_THREAD,0),getpriority(PRIO_PROCESS,getpid())); fflush(stdout);
    const int listener = socket(AF_INET, SOCK_STREAM, 0);
    if (listener < 0) return 1;
    int yes=1; setsockopt(listener, SOL_SOCKET, SO_REUSEADDR, &yes, sizeof(yes));
    sockaddr_in address{}; address.sin_family=AF_INET; address.sin_port=htons(43189);
    inet_pton(AF_INET, local, &address.sin_addr);
    if (bind(listener, reinterpret_cast<sockaddr*>(&address), sizeof(address)) || listen(listener, 4)) {
        perror("throughput listener"); close(listener); return 1;
    }
    printf("Synthetic throughput server ready on %s:43189; peer %s only; expires in 30 minutes.\n",local,peer); fflush(stdout);
    std::vector<Lane> lanes;
    const auto deadline = Clock::now() + std::chrono::minutes(30);
    try {
        for (const int count : {1,2,4}) {
            lanes.clear(); lanes.reserve(size_t(count));
            while (lanes.size() < size_t(count)) {
                if (Clock::now() >= deadline) throw std::runtime_error("No Windows test received before timeout");
                pollfd item{listener,POLLIN,0}; if (poll(&item,1,1000) <= 0) continue;
                sockaddr_in remote{}; socklen_t size=sizeof(remote);
                const int fd=accept(listener,reinterpret_cast<sockaddr*>(&remote),&size);
                if (fd < 0) continue;
                if (remote.sin_addr.s_addr != inet_addr(peer)) { close(fd); continue; }
                timeval timeout{3,0}; setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));
                std::array<unsigned char,16> header{}; size_t offset=0;
                while (offset<header.size()) {
                    const auto n=recv(fd,header.data()+offset,header.size()-offset,0);
                    if (n<=0) break; offset+=size_t(n);
                }
                if (offset!=header.size() || read32(header.data())!=0x54445046 || read16(header.data()+4)!=1 ||
                    read16(header.data()+6)!=count || read16(header.data()+8)!=lanes.size() ||
                    read16(header.data()+10)!=0 || read32(header.data()+12)!=duration) {
                    close(fd); throw std::runtime_error("Unexpected throughput handshake");
                }
                int capacity=8*1024*1024;
                setsockopt(fd,SOL_SOCKET,SO_SNDBUF,&capacity,sizeof(capacity));
                setsockopt(fd,SOL_SOCKET,SO_NOSIGPIPE,&yes,sizeof(yes));
                setsockopt(fd,IPPROTO_TCP,TCP_NODELAY,&yes,sizeof(yes));
                setsockopt(fd,SOL_SOCKET,SO_SNDTIMEO,&timeout,sizeof(timeout));
                if(fcntl(fd,F_SETFL,fcntl(fd,F_GETFL,0)|O_NONBLOCK)<0) { close(fd); throw std::runtime_error("Test socket mode failed"); }
                lanes.push_back({fd,0,false});
            }
            const auto start=Clock::now(), end=start+std::chrono::milliseconds(duration);
            std::vector<std::thread> workers;
            const std::vector<unsigned char> payload(262144,0x5a);
            for (auto& lane:lanes) workers.emplace_back([&lane,&payload,end] {
                const int qosError=pthread_set_qos_class_self_np(QOS_CLASS_USER_INTERACTIVE,0);
                if(qosError) { lane.failed=true; return; }
                describe(lane.fd,"start");
                auto snapshot=Clock::now();
                while (Clock::now()<end) {
                    const auto n=send(lane.fd,payload.data(),payload.size(),0);
                    if(n<0 && (errno==EAGAIN || errno==EWOULDBLOCK || errno==EINTR)) {
                        pollfd item{lane.fd,POLLOUT,0}; poll(&item,1,10); continue;
                    }
                    if(n<=0) { lane.failed=true; break; }
                    lane.bytes+=uint64_t(n);
                    if(Clock::now()-snapshot>=std::chrono::seconds(1)) { describe(lane.fd,"send"); snapshot=Clock::now(); }
                }
                describe(lane.fd,"finish");
                shutdown(lane.fd,SHUT_WR);
            });
            for(auto& worker:workers) worker.join();
            uint64_t bytes=0; bool failed=false;
            for(auto& lane:lanes) { bytes+=lane.bytes; failed|=lane.failed; close(lane.fd); lane.fd=-1; }
            const double seconds=std::chrono::duration<double>(Clock::now()-start).count();
            printf("lanes=%d synthetic_bytes=%llu seconds=%.3f queued_Gbps=%.3f failed=%d\n",count,
                static_cast<unsigned long long>(bytes),seconds,double(bytes)*8/seconds/1e9,int(failed)); fflush(stdout);
            if(failed) throw std::runtime_error("Synthetic send failed");
        }
        close(listener); return 0;
    } catch(const std::exception& e) {
        fprintf(stderr,"Throughput test: %s\n",e.what());
        for(auto& lane:lanes) if(lane.fd>=0) close(lane.fd);
        close(listener); return 1;
    }
}
