# Synthetic TCP receive test. No network settings, firewall, or video settings are changed.
$ErrorActionPreference = 'Stop'
$clients = @(Get-Process ThunderDisplayClient -ErrorAction SilentlyContinue)
$connections = @(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue | Where-Object { $_.OwningProcess -in $clients.Id -and $_.RemoteAddress -eq '10.0.0.2' -and $_.LocalAddress -eq '10.0.0.3' })
if (!$connections.Count) { throw 'Keep TD connected to Mac 10.0.0.2 via Windows 10.0.0.3 before running this test.' }
Write-Host 'Bandwidth check v2: 1, 2, then 4 TCP connections, about 30 seconds. Keep the Mac desktop still.'
Add-Type -TypeDefinition @'
using System;
using System.Diagnostics;
using System.Globalization;
using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Threading;
public static class TDThroughputCheck {
    public static string PartialResults = "";
    public static string Run() {
        var report = new StringBuilder();
        foreach (int count in new int[] {1,2,4}) {
            var sockets = new Socket[count]; var threads = new Thread[count];
            var bytes = new long[count]; var failures = new string[count];
            try {
                // Connect in lane order to keep the server handshake deterministic.
                for(int i=0;i<count;i++) {
                    var socket = new Socket(AddressFamily.InterNetwork,SocketType.Stream,ProtocolType.Tcp);
                    sockets[i]=socket; socket.Bind(new IPEndPoint(IPAddress.Parse("10.0.0.3"),0));
                    // The v1 .NET test connection advertised only 65,280 bytes.
                    // For this fixed bulk test, reserve 8 MiB before the SYN.
                    // This affects only the disposable test sockets, not TD or global TCP settings.
                    socket.ReceiveBufferSize=8*1024*1024;
                    if(socket.ReceiveBufferSize<8*1024*1024) throw new Exception("Test receive buffer was not applied");
                    socket.Blocking=false;
                    try { socket.Connect(new IPEndPoint(IPAddress.Parse("10.0.0.2"),43189)); }
                    catch(SocketException e) { if(e.SocketErrorCode!=SocketError.WouldBlock && e.SocketErrorCode!=SocketError.InProgress) throw; }
                    if(!socket.Poll(3000000,SelectMode.SelectWrite) || (int)socket.GetSocketOption(SocketOptionLevel.Socket,SocketOptionName.Error)!=0)
                        throw new Exception("Mac test server not available. Ask to restart the Mac bandwidth test.");
                    socket.Blocking=true; socket.NoDelay=true; socket.ReceiveTimeout=15000; socket.SendTimeout=3000;
                    byte[] header={0x54,0x44,0x50,0x46,0,1,0,(byte)count,0,(byte)i,0,0,0,0,0x1f,0x40};
                    int offset=0;
                    while(offset<header.Length) { int sent=socket.Send(header,offset,header.Length-offset,SocketFlags.None); if(sent<=0) throw new Exception("Handshake failed"); offset+=sent; }
                }
                var watch=Stopwatch.StartNew();
                for(int i=0;i<count;i++) {
                    int lane=i;
                    threads[i]=new Thread(delegate() {
                        try {
                            byte[] buffer=new byte[1048576];
                            for(;;) { int received=sockets[lane].Receive(buffer,SocketFlags.None); if(received==0) break; bytes[lane]+=received; }
                        } catch(Exception e) { failures[lane]=e.Message; }
                    });
                    threads[i].Priority=ThreadPriority.AboveNormal;
                    threads[i].Start();
                }
                foreach(var thread in threads) thread.Join(); watch.Stop();
                long total=0;
                for(int i=0;i<count;i++) { if(failures[i]!=null) throw new Exception(failures[i]); total+=bytes[i]; }
                if(watch.Elapsed.TotalSeconds<7.5 || total==0) throw new Exception("Incomplete throughput test");
                report.AppendLine(String.Format(CultureInfo.InvariantCulture,"connections={0} received_bytes={1} seconds={2:F3} actual_receive_Gbps={3:F3} receive_buffer_bytes={4}",count,total,watch.Elapsed.TotalSeconds,total*8.0/watch.Elapsed.TotalSeconds/1e9,sockets[0].ReceiveBufferSize));
                PartialResults=report.ToString();
            } finally { foreach(var socket in sockets) if(socket!=null) socket.Close(); }
        }
        return report.ToString();
    }
}
'@
try { $results = [TDThroughputCheck]::Run() }
catch { $results = [TDThroughputCheck]::PartialResults + "`r`nTest failed: " + $_.Exception.Message }
$text = 'ThunderDisplay synthetic link throughput v2 ' + (Get-Date -Format o) + "`r`n" + $results
$text += "`r`nTD stays connected; synthetic generated bytes only; no screenshot or input data collected.`r`n"
$text += (Get-NetIPInterface -AddressFamily IPv4 | Where-Object { $_.InterfaceIndex -in @(Get-NetIPAddress -IPAddress '10.0.0.3').InterfaceIndex } | Select-Object InterfaceAlias,NlMtu | Out-String)
$file = Join-Path ([Environment]::GetFolderPath('Desktop')) ('ThunderDisplay-Bandwidth-Report-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.txt')
[IO.File]::WriteAllText($file,$text,(New-Object System.Text.UTF8Encoding($true)))
Write-Host $results
Write-Host ('Report saved: ' + $file)
Start-Process notepad.exe -ArgumentList ('"' + $file + '"')
